//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceContract
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventario", Namespace="http://schemas.datacontract.org/2004/07/ServiceContract")]
    public partial class Inventario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantidadField;
        
        private int CodigoField;
        
        private string NombreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventarioFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContract")]
    public partial class InventarioFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://demoswcf/inventario", ConfigurationName="Inventario")]
public interface Inventario
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://demoswcf/inventario/ObtenerInventario", ReplyAction="http://demoswcf/inventario/Inventario/ObtenerInventarioResponse")]
    ServiceContract.Inventario[] ObtenerInventario();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://demoswcf/inventario/ObtenerInventario", ReplyAction="http://demoswcf/inventario/Inventario/ObtenerInventarioResponse")]
    System.Threading.Tasks.Task<ServiceContract.Inventario[]> ObtenerInventarioAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://demoswcf/inventario/AgregarInventario", ReplyAction="http://demoswcf/inventario/Inventario/AgregarInventarioResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ServiceContract.InventarioFault), Action="http://demoswcf/inventario/FaultInventario", Name="InventarioFault", Namespace="http://schemas.datacontract.org/2004/07/ServiceContract")]
    void AgregarInventario(int codigo, string nombre, int cantidad);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://demoswcf/inventario/AgregarInventario", ReplyAction="http://demoswcf/inventario/Inventario/AgregarInventarioResponse")]
    System.Threading.Tasks.Task AgregarInventarioAsync(int codigo, string nombre, int cantidad);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface InventarioChannel : Inventario, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class InventarioClient : System.ServiceModel.ClientBase<Inventario>, Inventario
{
    
    public InventarioClient()
    {
    }
    
    public InventarioClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public InventarioClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InventarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public InventarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ServiceContract.Inventario[] ObtenerInventario()
    {
        return base.Channel.ObtenerInventario();
    }
    
    public System.Threading.Tasks.Task<ServiceContract.Inventario[]> ObtenerInventarioAsync()
    {
        return base.Channel.ObtenerInventarioAsync();
    }
    
    public void AgregarInventario(int codigo, string nombre, int cantidad)
    {
        base.Channel.AgregarInventario(codigo, nombre, cantidad);
    }
    
    public System.Threading.Tasks.Task AgregarInventarioAsync(int codigo, string nombre, int cantidad)
    {
        return base.Channel.AgregarInventarioAsync(codigo, nombre, cantidad);
    }
}
